name: ai-agent-csharp-pipeline
steps:
  - name: get_input
    type: shell
    command: dotnet run --project src/InputHandler

  - name: ask_openai
    type: shell
    command: dotnet run --project src/AzureAIClient

  - name: show_response
    type: shell
    command: dotnet run --project src/ResponseFormatter
